import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
  /**
   * https://kotlinlang.org/
   */
  const val kotlin_annotation_processing_gradle: String =
      "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" + Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_scripting_compiler_embeddable: String =
      "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" + Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_test: String = "org.jetbrains.kotlin:kotlin-test:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_test_junit: String = "org.jetbrains.kotlin:kotlin-test-junit:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://junit.org/junit5/
   */
  const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api:" +
      Versions.org_junit_jupiter

  /**
   * https://junit.org/junit5/
   */
  const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine:" +
      Versions.org_junit_jupiter

  const val vertx_core: String = "io.vertx:vertx-core:" + Versions.io_vertx

  const val vertx_junit5: String = "io.vertx:vertx-junit5:" + Versions.io_vertx

  const val vertx_lang_kotlin: String = "io.vertx:vertx-lang-kotlin:" + Versions.io_vertx

  const val vertx_lang_kotlin_coroutines: String = "io.vertx:vertx-lang-kotlin-coroutines:" +
      Versions.io_vertx

  const val vertx_stack_depchain: String = "io.vertx:vertx-stack-depchain:" + Versions.io_vertx

  const val vertx_unit: String = "io.vertx:vertx-unit:" + Versions.io_vertx

  const val vertx_web: String = "io.vertx:vertx-web:" + Versions.io_vertx

  const val vertx_web_api_contract: String = "io.vertx:vertx-web-api-contract:" + Versions.io_vertx

  const val com_github_johnrengelman_shadow_gradle_plugin: String =
      "com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:" +
      Versions.com_github_johnrengelman_shadow_gradle_plugin

  const val org_jlleitschuh_gradle_ktlint_gradle_plugin: String =
      "org.jlleitschuh.gradle.ktlint:org.jlleitschuh.gradle.ktlint.gradle.plugin:" +
      Versions.org_jlleitschuh_gradle_ktlint_gradle_plugin

  const val de_fayard_refreshversions_gradle_plugin: String =
      "de.fayard.refreshVersions:de.fayard.refreshVersions.gradle.plugin:" +
      Versions.de_fayard_refreshversions_gradle_plugin

  const val org_jetbrains_kotlin_kapt_gradle_plugin: String =
      "org.jetbrains.kotlin.kapt:org.jetbrains.kotlin.kapt.gradle.plugin:" +
      Versions.org_jetbrains_kotlin_kapt_gradle_plugin

  const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
      "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" +
      Versions.org_jetbrains_kotlin_jvm_gradle_plugin

  const val io_vertx_vertx_plugin_gradle_plugin: String =
      "io.vertx.vertx-plugin:io.vertx.vertx-plugin.gradle.plugin:" +
      Versions.io_vertx_vertx_plugin_gradle_plugin

  const val com_moowork_node_gradle_plugin: String =
      "com.moowork.node:com.moowork.node.gradle.plugin:" + Versions.com_moowork_node_gradle_plugin

  /**
   * http://logback.qos.ch
   */
  const val logback_classic: String = "ch.qos.logback:logback-classic:" + Versions.logback_classic

  /**
   * https://github.com/MicroUtils/kotlin-logging
   */
  const val kotlin_logging: String = "io.github.microutils:kotlin-logging:" +
      Versions.kotlin_logging

  /**
   * http://www.slf4j.org
   */
  const val slf4j_api: String = "org.slf4j:slf4j-api:" + Versions.slf4j_api

  /**
   * https://github.com/pinterest/ktlint
   */
  const val ktlint: String = "com.pinterest:ktlint:" + Versions.ktlint
}
